### ISSUE TITLE
UI doesnt show up

### ISSUE THREAD

**Issue by MarcoPolo1990** [MidnightsFX/Valheim_Fortress#1]
When interacting with the shrine nothing happens :

![892970_20231031192203_1](https://github.com/MidnightsFX/Valheim_Fortress/assets/1532162/d26d6bb6-6053-4480-b52a-f0a420a8b8ff)

**Comment by MidnightsFX** [comment]
Thanks for the report!
Was this single player? Local server? Or dedicated?

Also, I assume you were not holding the inventory key, or esc?

**Comment by MidnightsFX** [comment]
This should be fixed in 0.5.1, if it isn't please re-open!
