### ISSUE TITLE
Error on multiplayer join after interacting with wild shrine

### ISSUE THREAD

**Issue by Visteus** [MidnightsFX/Valheim_Fortress#13]
![valheim fortress error](https://github.com/MidnightsFX/Valheim_Fortress/assets/39381505/6eb4d578-d156-4f65-9b95-e8d6df23556c)

Basically title. After I interacted with a wild shrine (with wrong items, since I didnt know what it needed yet), anytime a friend tried joining they would get a black screen and I would see this error pop up in the logs via Jotunn. Similar error popped up on going back and interacting with the wild shrine.

**Comment by MidnightsFX** [comment]
What version is this on? This should be fixed on `0.20.3`

**Comment by Visteus** [comment]
We are both running 0.20.3, latest we pulled from Thunderstore

**Comment by MidnightsFX** [comment]
I've got a build that should fix this, will be testing out and push to thunderstore/nexus once I verify

**Comment by MidnightsFX** [comment]
Ok `0.20.4` is out, and should fix this. Please give it a try when you get the chance! If you still have issues I'll likely need a lot more information to debug.

**Comment by Visteus** [comment]
Took some time to give it a test, but so far seems to be resolved with 0.20.4

**Comment by MidnightsFX** [comment]
Glad to hear! Feel free to reopen or bug me again if there are issues.
