### ISSUE TITLE
Remaining creatures :0

### ISSUE THREAD

**Issue by SquareBall789** [MidnightsFX/Valheim_Fortress#4]
Upon starting a new wave no creatures spawn, activating the shrine says "remaining creatures: 0"
(using version 0.7.1)
this appears in the log upon shrine activation:

[Info   :ValheimFortress.Challenge.Spawner] Spawn portals started
[Error  : Unity Log] ArgumentException: Texture2D.SetPixels: the size of data to be written to would result in writing outside the target buffer bounds. (Texture 'AttackOverlay')
Stack trace:
UnityEngine.Texture2D.SetPixels (System.Int32 x, System.Int32 y, System.Int32 blockWidth, System.Int32 blockHeight, UnityEngine.Color[] colors, System.Int32 miplevel) (at <50b18efe22344b9eb3b7d77b08ea287f>:0)
UnityEngine.Texture2D.SetPixels (System.Int32 x, System.Int32 y, System.Int32 blockWidth, System.Int32 blockHeight, UnityEngine.Color[] colors) (at <50b18efe22344b9eb3b7d77b08ea287f>:0)
ValheimFortress.Challenge.Spawner.DrawMapOverlayAndPortals (UnityEngine.Vector3[] remote_spawns) (at <bf7a8935914d4aa6887e3cf099c37b5d>:0)
ValheimFortress.Challenge.Spawner.TrySpawningHoard (System.Collections.Generic.List`1[T] hoards, System.Boolean siege_mode, UnityEngine.GameObject shrine) (at <bf7a8935914d4aa6887e3cf099c37b5d>:0)
ValheimFortress.Challenge.Levels.generateRandomWaveWithOptions (System.Int16 level, System.Boolean hard_mode, System.Boolean boss_mode, System.Boolean siege_mode, UnityEngine.GameObject shrine) (at <bf7a8935914d4aa6887e3cf099c37b5d>:0)
ValheimFortress.Challenge.UI.StartChallenge () (at <bf7a8935914d4aa6887e3cf099c37b5d>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <50b18efe22344b9eb3b7d77b08ea287f>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <50b18efe22344b9eb3b7d77b08ea287f>:0)
UnityEngine.UI.Button.Press () (at <042da27c9af642978a8a5138113c4eed>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <042da27c9af642978a8a5138113c4eed>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <042da27c9af642978a8a5138113c4eed>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <042da27c9af642978a8a5138113c4eed>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by MidnightsFX** [comment]
I'll look into this shortly, think I know what might be causing this.

**Comment by MidnightsFX** [comment]
This should be fixed in 0.7.2

**Comment by SquareBall789** [comment]
Can confirm this is fixed!
