### ISSUE TITLE
Log spam causing crash

### ISSUE THREAD

**Issue by SquareBall789** [MidnightsFX/Valheim_Fortress#6]
Upon starting Meadow-5 game crashed. (I tried meadow-1 5 minutes previously which worked as intended)

Using VF version 0.7.2

Log:
[LogOutput.log](https://github.com/MidnightsFX/Valheim_Fortress/files/13341245/LogOutput.log)

**Comment by SquareBall789** [comment]
also sorry about not following up on the skeleton issue, will do so soon!

**Comment by MidnightsFX** [comment]
This is likely on happening on wave 5,10,15. I'll work on adding some more safety checks for this.

What is happening is the shrine is trying to determine what will be in the wave, and there are not enough creatures unlocked for the particular level to ever form a valid spawn.

I've already got the immediate issue patched and that should be out in the next update, likely later today.

**Comment by SquareBall789** [comment]
ahh thanks man, I had a second look at that skeleton issue i was having but it works normally in single player, likely only an issue in multiplayer.

**Comment by MidnightsFX** [comment]
I'd be very interested if you are still experiencing the issue in multiplayer dedicated or not, I believe I got that fixed but if you do find its still reoccurring feel free to re-open the issue or make a new one and provide me some more information on the conditions you are seeing it occur in.

**Comment by MidnightsFX** [comment]
this is fixed in 0.7.3
