### ISSUE TITLE
Way to "lose" wave (enhancement)

### ISSUE THREAD

**Issue by SquareBall789** [MidnightsFX/Valheim_Fortress#7]
add a way for monsters to win if shrine is destroyed or player killed?

(accidently summoned swamp wave and realized creatures just sort of hang around, they are far too powerful for me lol)

**Comment by MidnightsFX** [comment]
Ahh yes, this is something I had considered- causing the creatures to despawn after a long period of time. Or after they destroy the shrine.

If you are having this issue in singleplayer for the time being you can run dev commands to kill the creatures to remove them if need be `killenemies` should do it. You will need `devcommands` enabled.

**Comment by MidnightsFX** [comment]
This is now available in `0.9.12`!
